<?php

namespace Tests\Unit\Models;

use App\Models\Laboratory;
use Illuminate\Database\Eloquent\Collection;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LaboratoryTest extends TestCase
{
    use RefreshDatabase;

    private $laboratory;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->laboratory = create(Laboratory::class);
    }

    /** @test */
    public function a_laboratory_can_generate_its_own_unique_code()
    {
        $laboratory = create(Laboratory::class);
        $this->assertNotNull($laboratory->chcode);
    }

    /** @test */
    public function a_laboratory_has_many_profile_shares()
    {
        $this->assertInstanceOf(Collection::class, $this->laboratory->profileShares);
    }

    /** @test */
    public function a_laboratory_has_many_patients()
    {
        $this->assertInstanceOf(
            Collection::class,
            $this->laboratory->patients()->get()
        );
    }

}
