<?php

namespace App\Models;

use App\Helpers\RecordLogger;
use Illuminate\Database\Eloquent\Model;

class Diagnosis extends Model
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }


    protected $guarded = [];

    // Diagnosis Belongs to A patient
    public function record()
    {
        return $this->belongsTo(MedicalRecord::class, 'record_id');
    }
    //Diagnosis Belongs to patient
    public function getPatientAttribute(){
        return $this->record->patient;
    }
    //Get the issuer of the diagnostics

}
